if (NOT CMAKE_BUILD_TYPE)
  set (CMAKE_BUILD_TYPE "Release")
endif ()

if (CMAKE_BUILD_TYPE STREQUAL "Debug")
  set (CMAKE_EXPORT_COMPILE_COMMANDS 1)
  set (DEBUG 1)
  set (TINTO_DEVEL_MODE 1)
  unset (NDEBUG)
  mark_as_advanced (NDEBUG TINTO_DEVEL_MODE)

  if (CMAKE_C_COMPILER_ID STREQUAL "Clang" OR CMAKE_C_COMPILER_ID STREQUAL "GNU")
    set (CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -Wall -Wextra -Werror -std=c99 -pedantic")
    if (ENABLE_SAN)
      string (TOLOWER ${ENABLE_SAN} ENABLE_SAN)
    else ()
      set (ENABLE_SAN "off")
    endif ()

    if (${ENABLE_SAN} STREQUAL "asan" OR ${ENABLE_SAN} STREQUAL "on")
      set (CMAKE_EXE_LINKER_FLAGS "-fno-omit-frame-pointer -fsanitize=address")
    elseif (${ENABLE_SAN} STREQUAL "msan")
      set (CMAKE_EXE_LINKER_FLAGS "-fno-omit-frame-pointer -fsanitize=memory")
    elseif (${ENABLE_SAN} STREQUAL "tsan")
      set (CMAKE_EXE_LINKER_FLAGS "-fno-omit-frame-pointer -fsanitize=thread")
    endif ()
  endif ()
endif ()
